language: c

env:
  global:
    - LUAROCKS=2.2.0beta1

  matrix:
    - LUA=lua5.1
    # - LUA=lua5.2
    # - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh

install:
  - sudo apt-get install libzmq3
  - sudo apt-get install libzmq3-dev
  - sudo luarocks install lunitx
  - sudo luarocks install date
  - sudo luarocks install luafilesystem
  - sudo luarocks install lua-path
  - sudo luarocks install lzmq
  - sudo luarocks install lua-llthreads2
  - sudo luarocks install lanes
  - sudo luarocks make rockspecs/lua-log-scm-0.rockspec
  - sudo luarocks install luasocket

script:
  - cd test
  - lua -v
  - lunit.sh test_file_writer.lua
  - lunit.sh test_basic.lua

notifications:
  email:
    on_success: change
    on_failure: always